version: "3"
services: 
  db:
    image: postgres:latest
    container_name: db-container
    environment:
      POSTGRES_PASSWORD: csc301
      POSTGRES_USER: summercamp
      POSTGRES_DB: summercamp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./summer_camp_schema.sql:/docker-entrypoint-initdb.d/summer_camp_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U summercamp -d summercamp_db"]
      interval: 1s
      timeout: 5s
      retries: 5

  app:
    image: my-node-app
    container_name: api-container
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    
volumes:
  postgres-data: